### ISSUE TITLE
Need to automatically install numpy to EB instance

### ISSUE THREAD

**Issue by tskluzac** [xtracthub/xtracthub-service#11]
So, if you try to install numpy (here it happened through installing pymatgen), then we ran into the following issue: 

(apparently the issue is avoided using --user in pip install line, but no work-around for requirements.txt entry)

-------------------------------------
/var/log/eb-activity.log
-------------------------------------
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
          DirectorySandbox(setup_dir).run(runner)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
          return func()
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
          _execfile(setup_script, ns)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-93wtjji4/numpy-1.18.1/setup.py", line 488, in <module>
        File "/tmp/easy_install-93wtjji4/numpy-1.18.1/setup.py", line 469, in setup_package
        File "/tmp/easy_install-93wtjji4/numpy-1.18.1/setup.py", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-007xq4jk/pymatgen/setup.py", line 187, in <module>
          'get_environment = pymatgen.cli.get_environment:main',
        File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
          self.fetch_build_eggs(attrs['setup_requires'])
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
          replace_conflicting=True,
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
          dist = best[req.key] = env.best_match(req, ws, installer)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
          return self.obtain(req, installer)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
          return installer(requirement)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
          return cmd.easy_install(req)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
          run_setup(setup_script, args)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
          raise
        File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
          yield
        File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
          saved_exc.resume()
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
          six.reraise(type, exc, self._tb)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
          yield saved
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
          yield
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
          DirectorySandbox(setup_dir).run(runner)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
          return func()
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
          _execfile(setup_script, ns)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
          exec(code, globals, locals)
        File "/tmp/easy_install-93wtjji4/numpy-1.18.1/setup.py", line 488, in <module>
        File "/tmp/easy_install-93wtjji4/numpy-1.18.1/setup.py", line 469, in setup_package
        File "/tmp/easy_install-93wtjji4/numpy-1.18.1/setup.py", line 275, in generate_cython
      RuntimeError: Running cythonize failed!
      Cythonizing sources
      
      ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-007xq4jk/pymatgen/
  You are using pip version 9.0.1, however version 20.0.2 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  2020-03-17 03:55:54,792 ERROR    Error installing dependencies: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1
  Traceback (most recent call last):
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 22, in main
      install_dependencies()
    File "/opt/elasticbeanstalk/hooks/appdeploy/pre/03deploy.py", line 18, in install_dependencies
      check_call('%s install -r %s' % (os.path.join(APP_VIRTUAL_ENV, 'bin', 'pip'), requirements_file), shell=True)
    File "/usr/lib64/python2.7/subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  CalledProcessError: Command '/opt/python/run/venv/bin/pip install -r /opt/python/ondeck/app/requirements.txt' returned non-zero exit status 1 (Executor::NonZeroExitStatus)

**Comment by tskluzac** [comment]
Done. Fixed by copying the 'problem' from https://stackoverflow.com/questions/28099881/how-can-i-install-matplotlib-for-my-aws-elastic-beanstalk-application
